CREATE TABLE IF NOT EXISTS beekeeper (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  village TEXT,
  experience_years INTEGER NOT NULL DEFAULT 0,
  bio TEXT,
  upi_id TEXT,
  promotion_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
  rating_avg DOUBLE PRECISION NOT NULL DEFAULT 0,
  rating_count INTEGER NOT NULL DEFAULT 0,
  photo_url TEXT,
  collective_name TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  site_people TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS batch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beekeeper_id BIGINT NOT NULL REFERENCES beekeeper(id),
  hive_id TEXT NOT NULL,
  harvest_date DATE NOT NULL,
  location TEXT,
  honey_type TEXT,
  flower_source TEXT,
  horticulture_notes TEXT,
  harvest_method TEXT,
  weight_kg DOUBLE PRECISION,
  prev_hash TEXT,
  hash TEXT UNIQUE NOT NULL,
  scan_secret TEXT,
  packer_name TEXT,
  ca_number TEXT,
  packing_date DATE,
  best_before DATE,
  lot_number TEXT,
  mrp DOUBLE PRECISION,
  net_weight DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pooled_lot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_name TEXT,
  plant_date DATE NOT NULL,
  pooled_hash TEXT UNIQUE NOT NULL,
  prev_hashes TEXT NOT NULL,
  weight_kg DOUBLE PRECISION,
  scan_secret TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rating (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beekeeper_id BIGINT NOT NULL REFERENCES beekeeper(id),
  batch_hash TEXT NOT NULL,
  scan_secret TEXT,
  consumer_id TEXT,
  stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (batch_hash, scan_secret)
);

CREATE TABLE IF NOT EXISTS hive_reading (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hive_id TEXT NOT NULL,
  beekeeper_id BIGINT REFERENCES beekeeper(id),
  temperature DOUBLE PRECISION,
  humidity DOUBLE PRECISION,
  weight DOUBLE PRECISION,
  sound_db DOUBLE PRECISION,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  flag TEXT
);

CREATE INDEX IF NOT EXISTS idx_batch_hash ON batch(hash);
CREATE INDEX IF NOT EXISTS idx_batch_beekeeper ON batch(beekeeper_id);
CREATE INDEX IF NOT EXISTS idx_batch_date ON batch(harvest_date);
CREATE INDEX IF NOT EXISTS idx_hive_hiveid ON hive_reading(hive_id);
CREATE INDEX IF NOT EXISTS idx_beekeeper_collective ON beekeeper(collective_name);
